load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "ftxui",
    srcs = [
        "main.cpp",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@ftxui",
    ],
)
