load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "vbox",
    srcs = [
        "vbox.cpp",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@ftxui",
    ],
)

cc_binary(
    name = "homescreen",
    srcs = [
        "homescreen.cpp",
    ],
    visibility = [
        "//visibility:public",
    ],
    deps = [
        "@ftxui",
    ],
)
